name: Update README with LeetCode solutions

on:
  push:
    paths:
      - 'algorithms/**'
      - '.github/scripts/generate_table.py'
      - '.github/workflows/update-readme.yml'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install requests
        run: pip install requests

      - name: Generate README solutions table
        run: python .github/scripts/generate_table.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "Update README with LeetCode solutions"
          git push
